name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Get current date and time
      if: github.event_name == 'push'
      id: date
      run: echo "RELEASE_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Create dynamic release name
      if: github.event_name == 'push'
      run: |
        export RELEASE_NAME="release-${{ github.sha }}-${{ env.RELEASE_DATE }}"
        echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV

    - name: Create GitHub Release
      if: github.event_name == 'push'
      env:
        GH_TOKEN: ${{ secrets.FILEUPLOADAPI_TOKEN }}
      run: |
         gh release create ${{ env.RELEASE_NAME }} --title "Automated Release ${{ env.RELEASE_DATE }}" --notes "Automated release created on ${{ env.RELEASE_DATE }}" --repo SuhasSahadev/fileuploadapi

    - name: Upload Package to GitHub Release
      if: github.event_name == 'push'
      env:
        GH_TOKEN: ${{ secrets.FILEUPLOADAPI_TOKEN }}
      run: |
         gh release upload ${{ env.RELEASE_NAME }} dist/*.tar.gz dist/*.whl --repo SuhasSahadev/fileuploadapi